### ISSUE TITLE
Feature request:  Configure OSD position

### ISSUE THREAD

**Issue by derkommutator** [hoglet67/RGBtoHDMI#195]
I'm using RGB2HDMI in an installation where part of the screen is obscured by a bezel.  This is no problem for the video itself, because it can be freely positioned via the min/max settings.  But the OSD menu is cut off on the left hand side.  I can see enough to navigate the menus with a bit of effort, but it would be nice if there were a way to specify an offset for the OSD.

Thanks for this fantastic project!  :)

**Comment by IanSB** [comment]
I'll look at adding something in a future version but in the meantime you may be able to achieve the same result by editing the config file.

Load config.txt from the SD card into a text editor and add the following lines at the bottom of the # Common video settings block:

overscan_left=10
overscan_right=10
overscan_top=10
overscan_bottom=10

and save the file. This will reduce the active screen area by 10 pixels all around and you can experiment by varying the sizes further.

reboot the Pi after re-inserting the SD card.

**Comment by derkommutator** [comment]
Ah, I hadn't realised those settings exist.  Honestly those are a better approach to my situation anyway, since all four borders of the screen are occluded and will never be used for anything.  Better to make them completely off limits.  Thanks!

**Comment by derkommutator** [comment]
Unfortunately, this workaround does not work, because while it does reduce the active screen area for the input, it does not affect the menu positioning.  I'll reopen this issue so that it may remain a feature request for later consideration.  It's not a dealbreaker problem for me, just makes working the menus a little more ... challenging.  ;)

**Comment by derkommutator** [comment]
(Ignore open/close there.  I managed to confuse myself (not the first time).  This workaround does the job.

**Comment by Gun-neR** [comment]
I just started using my RGBtoHDMI again after a couple of years... Everything works and I don't want to update firmware if I don't need to.  Only issue I have is the same as the OP...  My OSD is cut off on the top and left.  I like the rest of the borders the way they are and don't want to move them further in.  

So, was the OSD position ever made adjustable in later firmware? Or should I just live with it as is.

![Image](https://github.com/user-attachments/assets/fa108878-20f3-41e4-95e2-79da33d43c2d)

**Comment by IanSB** [comment]
@Gun-neR 

There isn't a specific setting to do that but there is usually a setting in the TV that controls that form of scaling.
The TV is zooming in on the image and cropping the edges like that because on older TV signals there is sometimes 'garbage' at the edges of the video.
Try adjusting the aspect ratio setting in the TV (not RGBtoHDMI) the correct aspect ratio setting might be something like 'full scan' or 'exact scan' or 'just scan'. Sometimes you might have to select "PC" mode for that input as a PC connected to that input would similarly have the edges like the start button cropped off.

There have been updates to the C128 profiles over the past couple of years including support for some of the custom demo modes and PETSCII_Robots plus lumacode support for 40 column mode and audio (requires extra hardware).

**Comment by Gun-neR** [comment]
Thanks for response.

I use this monitor for a few computers, so have already adjusted it's internal "cropping" for such, so that isn't it.

But it is good to know about the updated profiles for the C128... I have already had to make many adjustments for various programs due sync issues, etc.  Even though I seem to have it all running OK now... Except, of course, if I want to make the screen full zoom, then the OSD is still cropped by one character... And missing that first letter can really mess up the mind when reading ;)  Odd the OSD was never adjustable in the first place??

I have no need for the audio add-on, as I run the Ultimate II+L with external speakers for it's SID.  But I might consider updating the firmware after all, just to check out the updated profiles.

**Comment by Gun-neR** [comment]
Updated, but opps... I probably should have left it alone :P  Back to the flashing screen with GunFright VDC and can't seem to fix it.  I will open up a new issue with details.
