### ISSUE TITLE
Color Computer 3 captures are the wrong aspect ratio.

### ISSUE THREAD

**Issue by tlindner** [hoglet67/RGBtoHDMI#296]
The HDMI video produced by the device is perfect. But the screen shots it can save to PNG files are the wrong aspect ratio. Can the device be corrected to produce more accurate PNG files?
Here is how a CoCo 3 screen shot currently is saved:
![CoCo 3 Normal](https://user-images.githubusercontent.com/3808/179887035-9e8f8081-b3d2-486f-9af5-05be46b8f334.png)
This is what is produced by the CoCo 1 and 2 module that is more accurate.
![CoCo 2B Normal](https://user-images.githubusercontent.com/3808/179887111-21692d23-98a1-4127-9cc9-d5b6547af5d3.png)

**Comment by IanSB** [comment]
At the moment, the screencap function just dumps the framebuffer with some minimal integer scaling if appropriate. This works reasonably well when the video output is integer scaled but can result in bad aspect ratios when using interpolated scaling because the interpolated scaling is done by the Pi's hardware scaler.
You will usually get good results with a 1920x1080p monitor because virtually all profiles will integer scale with that but lower res monitors (or forcing interpolated scaling) will lead to poorer results.

What is the resolution of your monitor?

**Comment by tlindner** [comment]
That explains it.

RCA DETG160R 16" 1366x768.

**Comment by IanSB** [comment]
Depending on when it was made, your monitor might be able to accept 1920x1080 and scale that down so you could try changing the resolution setting in the main menu to that. If you don't get any display, hold the menu button down during reset / bootup to reset the resolution back to Auto.
