### ISSUE TITLE
Composite CGA colors are wrong with Raspberry Pi Zero.

### ISSUE THREAD

**Issue by A-Small-Mice** [hoglet67/RGBtoHDMI#302]
![capture2](https://user-images.githubusercontent.com/112596327/199528898-ebf52f23-77f1-4f2e-9b05-ccdf8164bef1.png)
![capture3](https://user-images.githubusercontent.com/112596327/199528925-52c211a0-707e-4cf9-a740-a6e8c69de770.png)

Please look at the images I posted. The colors are wrong. How can I solve this?

**Comment by IanSB** [comment]
@A-Small-Mice 

The colour artifact emulation only works for the mono 640x200 CGA mode with the Pi zero at the moment due to insufficient processor power to implement the full algorithm.
If you use a Pi zero 2W, Pi 3A, Pi 3A+, Pi 3B or Pi 3B+ the full algorithm will work and you should get the expected results.
Currently the Pi 2 and Pi 4 don't work with the  full algorithm but should work in the future.
