### ISSUE TITLE
Combined analog/digital board?

### ISSUE THREAD

**Issue by c0pperdragon** [hoglet67/RGBtoHDMI#309]
Would it be feasible to make a board that has a 16-pin digital connector as well as all the circuity of the analog board? With a little slider switch on the end where the SD card is (to be accessible through the hole in the case). This board would then behave either like the analog board, or like a simple 12-bit extender board. The input signals R3, G3, B3 would then be treated accordingly.
Combining both data paths could be done with some MUXes (the 74AHCT257 comes to mind). These MUXes would also act as a protection for the CPLD.
Using this board, a single RGBtoHDMI device (Raspberry Pi + CPLD board + analog/digital board) would then be usable for all supported machines, without the need to disassemble the RGBtoHDMI.  Legacy cables could be attached with adapters (12 pin to 16 pin, 6 pin to 16 pin).

**Comment by IanSB** [comment]
@c0pperdragon 
>Would it be feasible to make a board that has a 16-pin digital connector as well as all the circuity of the analog board?
The input signals R3, G3, B3 would then be treated accordingly.
Combining both data paths could be done with some MUXes (the 74AHCT257 comes to mind).

There is a potential issue::
The system is very sensitive to unequal propagation delays because the sampling position is set at multiples of the pixel clock so all 14 video and sync signals would have to be routed through switches rather than just the 10 on the main header to ensure they were co-timed and that would increase the number of ICs and resulting complexity of the pcb layout.
Also there might be a similar issue at the front end:
You could either switch the pins shared between analog and digital inputs which would introduce a similar delay problem or connect those pins to both the analog and digital inputs simultaneously which might inject digital noise into the analog inputs when used unterminated in analog mode or the capacitive loading of the analog circuitry might have an effect on propagation delay for those inputs when used in digital mode.  
I don't think it would be possible to get four of the above switching packages and pulldown resistors onto the underside of the board as clearance is limited but even if it was possible using a 4 or 6 layer board that still doesn't address the shared inputs. 

As the converters were originally pretty cheap to build with Pi zeros costing £5 and CPLDs about £3, the idea was to build one for each required interface rather than continually swapping boards. 
In my case, I am currently running 25 RGBtoHDMI converters simultaneously which are a mixture of Digital, Analog and PC connected to 25 computers and 14 monitors with 2 inputs each and that does allow me to test release versions quite quickly on a variety of configurations. (This project is getting quite expensive to maintain!)

Of course at the moment with CPLDs at £10+ and Pi zeros going for £30 on ebay things are no longer as cheap and I have been thinking about a universal solution but more along the lines of a larger single board and that might be more attractive now although it does look like supply issues are beginning to improve and I think raspberry Pi have indicated that availability should be much better in the next 3-4 months.
