### ISSUE TITLE
TI99 4/A TMS-RGB Palette.. 

### ISSUE THREAD

**Issue by dabonetn** [hoglet67/RGBtoHDMI#358]
I'm trying to get a NTSC TI99/4a working with the RGB2HDMI using a TMS-RGB.
I've got the latest analog board from Retrohack shack.

I'm getting a nice stable picture using a modified Camputers Lynx profile, But the colors are off.

sampling=5,5,5,5,5,5,5,0,1,0,5,0,0,0,0,0,0,0,0,0,100,256,100,256,100,256,256,256
geometry=60,25,256,252,280,286,3,2,3,0,6000000,384,5000,312,4,0,0

Screen Capture.
![capture0](https://github.com/hoglet67/RGBtoHDMI/assets/15277792/6142fba0-16ac-4006-bddc-3f178fbc1db0)

Emulator output showing proper colors.
![TI99-4A_Win994a_Simulator_Startup_Screen](https://github.com/hoglet67/RGBtoHDMI/assets/15277792/865b50b2-5b1b-4651-ae7e-84d793f71e0a)

Suggestions on where to get started?

**Comment by IanSB** [comment]
@dabonetn 

Getting the TI99/4a fully working with an analog RGBtoHDMI is quite difficult because the video voltage levels are a bit too close together to separate reliably. I have got it fully working both with a direct connection to the YUV output and using the TMS-RGB but the levels need adjusting as it warms up so it is not really a good solution.

However a lumacode board for the TI99 and other systems using the same video chip like the Colecovision has been developed and I now have a prototype for testing so that should be available in the future.

**Comment by dabonetn** [comment]
I just saw about the TMS board yesterday on his github. 
Can't wait.

**Comment by IanSB** [comment]
@dabonetn 
FYI:
https://github.com/c0pperdragon/LumaCode/issues/13#issuecomment-1902838176

**Comment by dabonetn** [comment]
Lumacode bought and installed... Works great. This can be closed.
