### ISSUE TITLE
C64 with VIC 2 Dizer from Copperdragon

### ISSUE THREAD

**Issue by LarsBorris** [hoglet67/RGBtoHDMI#369]
Hello, I installed the mod and, well I think the picture says it all.
I have tried every setting and now i am frustrated and need help, please, pretty please...
![capture0](https://github.com/hoglet67/RGBtoHDMI/assets/10630935/dd9ba30a-06a7-49b9-9307-54e71274e21a)

**Comment by LarsBorris** [comment]
The mod is this one:
https://www.tindie.com/products/c0pperdragon/vic-ii-dizer/

**Comment by IanSB** [comment]
@LarsBorris 
Are you using a Mono/Lumacode board or a normal analog RGBtoHDMI?

To work out if the problem is with the  C64 adapter or the RGBtoHDMI, the first thing to try is connecting the lumacode output of the C64 to a normal composite video monitor and post a photo of that output. It should look something like this:
(Click on the image below to view full size to eliminate any moire patterns)

![capture0](https://github.com/hoglet67/RGBtoHDMI/assets/45300594/547c9e26-c842-4c79-9216-c69ac32df99a)

You should get more specific support for the VICIIDizer on c0pperdragon's github here:
https://github.com/c0pperdragon/LumaCode/issues/3
So I suggest you post in that thread.

**Comment by LarsBorris** [comment]
@IanSB Thank you so much for taking the time to assist me.
I have tried to connect the copperdragon lumacode output to a tv as suggested, and I am getting the same color issues:
Complete black background with greyish text. Not like the one you supplied.
I will try and speak with copperdragon. Thanks again!
