### ISSUE TITLE
Delay calibration not working in modes 0-6

### ISSUE THREAD

**Issue by IanSB** [hoglet67/RGBtoHDMI#57]
The delay value selected by calibration in modes 0-6 is wrong, should be 5 on a Master 128 but comes up with the wrong value so the in band demo doesn't work.
It selects 8 in 3bpp mode and 2 in 6bpp mode it should be 5 in 3bpp mode and 1 in 6bpp so maybe related to the new CPLD design. It seems to work OK in mode 7.
Note I think the blank pixels in each character cell on the 8x8 and 12x20 fonts are in different places.

EDIT: Note the in band demo doesn't work in 6bpp mode so you have to use the debug lines to check it

**Comment by hoglet67** [comment]
Looks like both analyze_default_alignment and analyze_mode7_alignment assume a 4-bpp framebuffer.

Does it work if you change that setting back?

(I guess things have moved on since they were written)

Also, there's no guarantee the delay value that gets the correct alignment will be consistent across CPLD versions (or even between Mode0..6 and Mode 7).

Finally, it's probably a harmless bug that it can return 8; it should return 0 in that case. The result is missing a modulo DEFAULT_CHAR_WIDTH.
