### ISSUE TITLE
Improvement: Allow choice of OSD font (?) 

### ISSUE THREAD

**Issue by hoglet67** [hoglet67/RGBtoHDMI#92]
It's quite visually jarring on the Beeb for the menu font size to change dramatically between Mode7 and Mode 0..6.

(I have a strong liking for the 12x20 sized font and would like to be able to use it in all modes)

At the moment, it's explicitly disallowed in 8bpp framebuffers:
```
   if ((capinfo->sizex2 & 1) && (bufferCharWidth >= LINELEN) && (capinfo->bpp < 8)) {       // if frame buffer is large enough and not 8bpp use SAA5050 font
```

I gave it a quick try (by getting rid of the bpp check) and it seems to work fine.

What are the failure cases that made you always use the 8x8 font with 8pp framebuffers?

**Comment by IanSB** [comment]
It drops every other frame and also messes up the genlock a bit when the OSD is on screen.
Try running my modified ski slalom sideways scrolling test which is good for detecting frame drops. It also causes the red bar of the vsync indicator to glitch to the top of the screen. 

With the auto switching modes, a frame drop was seen as a timing/mode change which caused repeated glitching as it tried to determine the current mode although I implemented a workaround so that 2x frame timing was accepted as valid to stop most of that.

I think that the fast osd update will have to be reimplemented in assembler to get it working properly.
Have a look at the code generated by the compiler to see how efficient it is.
